name: fluent
description: "A diploma thesis project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.7.2
  camera: ^0.11.2
  camera_android: ^0.10.10+6
  get_it: ^8.2.0
  flutter_riverpod: ^3.0.0-dev.17
  google_mlkit_pose_detection: ^0.14.0

dev_dependencies:
  build_runner: ^2.7.0
  retrofit_generator: ^10.0.2
  flutter_lints: ^6.0.0
  custom_lint:
  riverpod_lint: ^3.0.0-dev.17

dependency_overrides:
  analyzer: 8.1.1

flutter:

  uses-material-design: true

  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Catamaran
      fonts:
        - asset: fonts/catamaran.ttf
        - asset: fonts/catamaran_bold.ttf
          weight: 700

    - family: Notosans
      fonts:
        - asset: fonts/notosans.ttf
