name: fluent
description: "A diploma thesis project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  retrofit: 4.7.2
  camera: 0.11.2
  camera_android: 0.10.10+7
  get_it: 8.2.0
  flutter_riverpod: 3.0.0
  google_mlkit_pose_detection: 0.14.0
  google_mlkit_face_detection: 0.13.1
  easy_video_editor: ^0.1.3

dev_dependencies:
  build_runner: 2.8.0
  retrofit_generator: 10.0.5
  flutter_lints: 6.0.0
  flutter_native_splash: 2.4.6

dependency_overrides:
  analyzer: 8.1.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Catamaran
      fonts:
        - asset: fonts/catamaran.ttf
        - asset: fonts/catamaran_bold.ttf
          weight: 700

    - family: Notosans
      fonts:
        - asset: fonts/notosans.ttf

flutter_native_splash:
  color: "#2b6a46"
  image: "assets/app_logo.png"